---
- name: Mount media drives
  hosts: server
  tasks:
      - name: Mount Media1 drive
        block:
          - name: Create the /media/Media1 directory
            file:
                 path: /media/Media1
                 state: directory
            become: yes
          - name: Write content of fstab to variable
            ansible.builtin.command: cat /etc/fstab
            register: fstab_contents
          - name: Write comment for fstab for Media1
            shell: 'echo "# Media1 Hard drive" | sudo tee -a /etc/fstab > /dev/null'
            when: fstab_contents.stdout.find('# Media1 Hard drive') == -1
            become: yes
          - name: Write mount details to fstab for Media1
            # tee prints the text to stdout, too. 
            # In order to mute it so it behaves more similar to shell appending (>>), route the stdout to /dev/null:
            shell: 'echo "UUID=2cc00b65-9d64-4b9a-8aba-d737903734f8 /media/Media1               ext4   defaults 2 2" | sudo tee -a /etc/fstab > /dev/null'
            when: fstab_contents.stdout.find('2cc00b65-9d64-4b9a-8aba-d737903734f8') == -1
            become: yes
      # - name: Reboot machine to mount the drives
      #   ansible.builtin.reboot:
      #   reboot_timeout: 10
      #   become: yes
