version: "3.5"
services:
  jellyfin:
    image: jellyfin/jellyfin
    container_name: jellyfin
    user: 1000:1000
    network_mode: "host"
    volumes:
      - /home/floma/jellyfin/config:/config
      - /home/floma/jellyfin/cache:/cache
      - /media/Media1:/media1
    restart: "unless-stopped"
